# You can register your runner following the tutorial below
# https://docs.gitlab.com/runner/register/

before_script:
  - cd API/
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test