# Image table
MACHINEID = "machineid"
ULLID = "ullid"
ACCOUNTED_INK_BLACK = "AccountedInkBlack"
ACCOUNTED_INK_CYAN = "AccountedInkCyan"
ACCOUNTED_INK_MAGENTA = "AccountedInkMagenta"
ACCOUNTED_INK_YELLOW = "AccountedInkYellow"
DATE = "date"
IMAGE_LENGTH = "ImageLength"
IMAGE_WIDTH = "ImageWidth"
MEDIA_TYPE = "mediacategory"
LOCAL_TIME = "LocalTime"

# units
ACCOUNTED_INK_BLACK_UNIT = "AccountedInkBlack|unit|"
ACCOUNTED_INK_CYAN_UNIT = "AccountedInkCyan|unit|"
ACCOUNTED_INK_MAGENTA_UNIT = "AccountedInkMagenta|unit|"
ACCOUNTED_INK_YELLOW_UNIT = "AccountedInkYellow|unit|"
IMAGE_LENGTH_UNIT = "ImageLength|unit|"
IMAGE_WIDTH_UNIT = "ImageWidth|unit|"
LOCAL_TIME_UNIT = "LocalTime|unit|"
