# Image table
MACHINEID = "machineid"
ULLID = "ullid"
ACCOUNTED_INK_BLACK = "AccountedInkBlack"
ACCOUNTED_INK_CYAN = "AccountedInkCyan"
ACCOUNTED_INK_MAGENTA = "AccountedInkMagenta"
ACCOUNTED_INK_YELLOW = "AccountedInkYellow"
DATE = "date"
IMAGE_LENGTH = "ImageLength"
IMAGE_WIDTH = "ImageWidth"
MEDIA_TYPE = "mediacategory"
LOCAL_TIME = "LocalTime"

# units
ACCOUNTED_INK_BLACK_UNIT = "accountedinkblack|unit|"
ACCOUNTED_INK_CYAN_UNIT = "accountedinkcyan|unit|"
ACCOUNTED_INK_MAGENTA_UNIT = "accountedinkmagenta|unit|"
ACCOUNTED_INK_YELLOW_UNIT = "accountedinkyellow|unit|"
IMAGE_LENGTH_UNIT = "imagelength|unit|"
IMAGE_WIDTH_UNIT = "imagewidth|unit|"
LOCAL_TIME_UNIT = "localtime|unit|"
