PREPROCESS_INK_USAGE = "preprocessinkusage"
PREPROCESS_MEDIA_TYPES_PER_MACHINE = "preprocestypespermachine"
PREPROCESS_SQM_PER_PRINT_MODE = "preprocesssqmperprintmode"
PREPROCESS_MEDIA_CATEGORY_USAGE = "preprocessmediacategoryusage"
PREPROCESS_TOP_TEN_PRINT_VOLUME = "preprocesstoptenprintvolume"
