#Image table
ULLID = "ullid"
ACCOUNTEDINKBLACK = "accountedinkblack"
ACCOUNTEDINKCYAN = "accountedinkcyan"
ACCOUNTEDINKMAGENTA = "accountedinkmagenta"
ACCOUNTEDINKYELLOW = "accountedinkyellow"
DATE = "date"
IMAGELENGTH = "imagelength"
IMAGEWIDTH = "imagewidth"
MEDIATYPE = "mediatype"