#Image table
ULLID = "ullid"
ACCOUNTED_INK_BLACK = "AccountedInkBlack"
ACCOUNTED_INK_BLACK_UNIT = "AccountedInkBlack|unit|"
ACCOUNTED_INK_CYAN = "AccountedInkCyan"
ACCOUNTED_INK_CYAN_UNIT = "AccountedInkCyan|unit|"
ACCOUNTED_INK_MAGENTA = "AccountedInkMagenta"
ACCOUNTED_INK_MAGENTA_UNIT = "AccountedInkMagenta|unit|"
ACCOUNTED_INK_YELLOW = "AccountedInkYellow"
ACCOUNTED_INK_YELLOW_UNIT = "AccountedInkYellow|unit|"
DATE = "date"
IMAGE_LENGTH = "ImageLength"
IMAGE_WIDTH = "ImageWidth"
MEDIA_TYPE = "mediacategory"
MACHINEID = "machineid"