#Image table
ULLID = "ullid"
ACCOUNTED_INK_BLACK = "accountedinkblack"
ACCOUNTED_INK_CYAN = "accountedinkcyan"
ACCOUNTED_INK_MAGENTA = "accountedinkmagenta"
ACCOUNTED_INK_YELLOW = "accountedinkyellow"
DATE = "date"
IMAGE_LENGTH = "imagelength"
IMAGE_WIDTH = "imagewidth"
MEDIA_TYPE = "mediacategory"