from config import read_image_column_name_config

pACCOUNTED_INK_BLACK_PAIR = ["image_col_name_accounted_ink_black", read_image_column_name_config.ACCOUNTED_INK_BLACK]
pACCOUNTED_INK_BLACK_PAIR_UNIT = ["image_col_name_accounted_ink_black_unit", read_image_column_name_config.ACCOUNTED_INK_BLACK_UNIT]
pACCOUNTED_INK_CYAN_PAIR = ["image_col_name_accounted_ink_cyan", read_image_column_name_config.ACCOUNTED_INK_CYAN]
pACCOUNTED_INK_CYAN_PAIR_UNIT = ["image_col_name_accounted_ink_cyan_unit", read_image_column_name_config.ACCOUNTED_INK_CYAN_UNIT]
pACCOUNTED_INK_MAGENTA_PAIR = ["image_col_name_accounted_ink_magenta", read_image_column_name_config.ACCOUNTED_INK_MAGENTA]
pACCOUNTED_INK_MAGENTA_PAIR_UNIT = ["image_col_name_accounted_ink_magenta_unit", read_image_column_name_config.ACCOUNTED_INK_MAGENTA_UNIT]
pACCOUNTED_INK_YELLOW_PAIR = ["image_col_name_accounted_ink_yellow", read_image_column_name_config.ACCOUNTED_INK_YELLOW]
pACCOUNTED_INK_YELLOW_PAIR_UNIT = ["image_col_name_accounted_ink_yellow_unit", read_image_column_name_config.ACCOUNTED_INK_YELLOW_UNIT]
pDATE_PAIR = ["image_col_name_date", read_image_column_name_config.DATE]
pIMAGE_LENGTH_PAIR = ["image_col_name_image_length", read_image_column_name_config.IMAGE_LENGTH]
pIMAGE_WIDTH_PAIR = ["image_col_name_image_width", read_image_column_name_config.IMAGE_WIDTH]
pMEDIA_TYPE_PAIR = ["image_col_name_media_type", read_image_column_name_config.MEDIA_TYPE]
pULLID_PAIR = ["image_col_name_ullid", read_image_column_name_config.ULLID]

